
var GRID_SIZE = 50;

var PLAYER_WIDTH = 22;
var PLAYER_HEIGHT = 40;

var FIRE_DAMAGE = 0.3334;

var HIT_FIRE_SPEED = 4.0;
var JUMP_SPEED = 8.0;
var MAX_FALL_SPEED = 8.0;
var MAX_WALK_SPEED = 4.0;
var MAX_FLYING_CORRECTION_SPEED = 1.5;
var MAX_FLYING_CORRECTION = 0.1;
var PLAYER_GRAVITY = 0.2;
var WALK_ACCELERATION = 0.22;
var SLIDING_FRICTION = 0.22;

